#!/bin/bash
sh -c 'git clone https://aur.archlinux.org/pantheon-settings-daemon-git.git'
sh -c 'cd pantheon-settings-daemon'
sh -c 'makechrootpkg -c -r $CHROOT'
sh -c 'pacman -U --asdeps pantheon-settings-daemon-git-1.0.0.r18.e4b709d-1-x86_64.pkg.tar.zst '
sh -c 'cd ..'
sh -c 'git clone https://aur.archlinux.org/pantheon-dock-instctl-git.git'
sh -c 'cd pantheon-dock-instctl-git'
sh -c 'makechrootpkg -c -r $CHROOT'
sh -c 'pacman -U --asdeps pantheon-dock-instctl-git-r2179.4a0b6af-1-x86_64.pkg.tar.zst '
sh -c 'cd ..'
sh -c 'git clone https://aur.archlinux.org/pantheon-session-git'
sh -c 'cd pantheon-session-git'
sh -c 'makechrootpkg -c -r $CHROOT -I ../pantheon-settings-daemon-git/pantheon-settings-daemon-git-1.0.0.r18.e4b709d-1-x86_64.pkg.tar.zst -I ../pantheon-dock-instctl-git/pantheon-dock-instctl-git-r2179.4a0b6af-1-x86_64.pkg.tar.zst'
sh -c 'pacman -U --asdeps pantheon-session-git-r148.48b482e-1-any.pkg.tar.zst'
